### ISSUE TITLE
The Hook interface is not respected

### ISSUE THREAD

**Issue by alquerci** [milesj/decoda#110]
Issue reported from helios-ag/FMBbCodeBundle#138

**Comment by milesj** [comment]
This should be fixed now.

**Comment by Discutea** [comment]
Hi

Sorry but this isn't solved.

The problem is actually the class /Decoda/Hook/CodeHook.php
It seems that the encoding and decoding of base64 do crash the class so it returns the empty
This also in the air to play on performance.

I have solved the problems by doing this,
http://pastebin.com/aNZxgGt4
 however, I don't pull request because I do not fully understand the utility of base64

This issue is high on large code

**Comment by milesj** [comment]
The base64 allows BBCode to be present within the code blocks and not be parsed. Your approach would not allow for that.

A thought just occurred to me that may make this easier to get around. Will prototype something real quick.

**Comment by milesj** [comment]
This *should* solve the issue once its tagged. https://github.com/milesj/decoda/commit/c2af0f5d681fe0a64a99d5722856fa2245354de0

**Comment by Discutea** [comment]
It does not work.

While I was looking for a solution, I realized that my first analysis was not good.
The problem is not base64 related, but preg_replace_callback() apparently is.

I ran a var_dump($string) at https://github.com/milesj/decoda/blob/master/src/Decoda/Hook/CodeHook.php#L31 so that we work with the same content. 
Here is the output: http://pastebin.com/27KV1jyw

And after executing:
die(var_dump( 
    preg_replace_callback('/\[code(.*?)\](((?R)|.)*?)\[\/code\]/is', array($this, '_encodeCallback'), $string)
));

It returns NULL on the production server (php7, nginx1.8, debian8) and timeout on the local server (xampp php5 apache2.2, Windows 10)

The error seems to be linked to the limit that preg_replace_callback() accepts. For more information: http://php.net/manual/pcre.configuration.php#ini.pcre.backtrack-limit

Sorry, despite my attempts I cannot manage to solve this problem.

**Comment by milesj** [comment]
Interesting. Thanks for the heads up. I'll mess around with replacing `preg_replace_callback()` as well.

Can you post the pastebin again? It seems to have expired.

**Comment by Discutea** [comment]
Oops Sorry 

http://pastebin.com/Py5FFwve

**Comment by alquerci** [comment]
Closed as this issue reported as been solved on version 6.7.2 by 967fa78dfef552014a268314199766a44945cb2e.

> The Hook interface is not respected

---

@DavidVerdier if your issue still actual (I as see it is) please create a dedicated ticket.

Indeed it return `null` but only if `pcre.backtrack_limit` is lower than 3108 (the default value is 10^6).

This issue can occurred but only if there is an issue on the php.ini configuration.

Details
---------

```php
<?php

$string = <<<'EOF'
Voici un petit bout de code tout simple rédigé en TCL pur établissant une connexion LINK avec un serveur InspIRCd 1.2.x/ 2.0.x. Le service en lui même est inutile, il sert simplement à répondre aux requêtes PING. [b]Fichier core.tcl[/b] [code="tcl"]# SySteM IRC Service # ==================== # Auteur: Diogene # ==================== # core.tcl # ==================== namespace eval service { set service(root) [file dirname [info script]] set service(modules) [file join $service(root) "modules"] set server(ip) "0.0.0.0" set server(port) "7000" set server(name)    "system.tonreseau.net" set server(passwd) "mot-de-passe" set server(desc)   "SySteM Advanced" set server(sid) "522" set bot(nick)   "SySteM" set bot(host)  "system.fr" set bot(ident)  "bot" set bot(real) "InspIRCd Server Test" set bot(uid) "522AAAAAA" set bot(chan) "#Services" } proc service::coreInit {args} { variable service variable server variable bot loadModule "irc.mod.tcl" ircConnection } proc service::ircConnection {args} { variable server variable bot if { [catch {socket $server(ip) $server(port)} sockID] } { puts "## Erreur reçue: $sockID " puts "## Arrêt automatique du service après détection d'erreur fatale..." exit 1 } fconfigure $sockID -buffering line fileevent $sockID readable [list [namespace current]::getData $sockID] irc::linkCreate $sockID $server(name) $server(passwd) $server(desc) $server(sid) irc::botCreate $sockID $bot(nick) $bot(ident) $bot(host) $bot(real) $server(sid) $bot(uid) $bot(chan) } proc service::getData {sockID} { variable server gets $sockID data if { [eof $sockID] } { close $sockID puts "EOF" exit 1 } irc::srvEvents $sockID $data $server(sid) } proc service::loadModule {moduleName} { variable service source $service(modules)/$moduleName } service::coreInit vwait _forever_[/code] [b]Fichier modules/irc.mod.tcl[/b] [code="tcl"]# SySteM IRC Service # ==================== # Auteur: Diogene # ==================== # irc.mod.tcl # ==================== namespace eval irc { variable ircd set ircd "inspircd"#Cette variable est inutile pour ce bout de code } proc irc::linkCreate {sockID name passwd desc sid} { puts $sockID "SERVER $name $passwd 0 $sid :$desc" puts $sockID ":$sid BURST [clock seconds]" puts $sockID ":$sid ENDBURST" } proc irc::botCreate {sockID nick ident host real sid uid chan} { puts $sockID ":$sid UID $uid [clock seconds] $nick $host $host $ident $host [clock seconds] +Siosw +ABCKNOQcdfgklnoqtx :$real" puts $sockID ":$uid JOIN $chan" puts $sockID ":$uid MODE $chan +o $nick" } proc irc::srvEvents {sockID data sid} { puts $data switch -exact [lindex $data 1] { "PING" { puts $sockID ":$sid PONG $sid :[lindex $data 2]" } } }[/code] Cordialement, Diogene.
EOF;

$hook = new CodeHook();

ini_set('pcre.backtrack_limit', 3107);
$result = $hook->beforeParse($string);
var_export($result);
echo PHP_EOL;
/*
 * Output
 *
 * NULL
 */

ini_set('pcre.backtrack_limit', 3108);
$result = $hook->beforeParse($string);
var_export($result);
echo PHP_EOL;
/*
 * Output
 *
 * 'Voici un petit bout de code tout simple rédigé en TCL pur établissant une connexion LINK avec un serveur InspIRCd 1.2.x/ 2.0.x. Le service en lui même est inutile, il sert simplement à répondre aux requêtes PING. [b]Fichier core.tcl[/b] [code="tcl"]$$CODE0$$[/code] [b]Fichier modules/irc.mod.tcl[/b] [code="tcl"]$$CODE1$$[/code] Cordialement, Diogene.'
 */

class CodeHook
{
    /**
     * Cached code blocks during the parsing process.
     *
     * @var array
     */
    protected $_cache = array();

    /**
     * Cache code blocks before parsing. It use regexp (?R) recursivity mask to deal with other nested code tags
     *
     * see http://php.net/manual/en/regexp.reference.recursive.php and http://stackoverflow.com/questions/2909588/regex-bbcode-perfecting-nested-quote#answer-2909930 for more informations
     *
     * @param string $string
     *
     * @return mixed
     */
    public function beforeParse($string)
    {
        $this->_cache = array();

        return preg_replace_callback('/\[code(.*?)\](((?R)|.)*?)\[\/code\]/is', array($this, '_encodeCallback'), $string);
    }

    /**
     * Encode content using base64.
     *
     * @param array $matches
     *
     * @return string
     */
    protected function _encodeCallback(array $matches)
    {
        $cacheSize = count($this->_cache);
        $this->_cache[$cacheSize] = $matches[2];

        return '[code' . $matches[1] . ']$$CODE' . $cacheSize . '$$[/code]';
    }
}
```
